import {
  Building2,
  Scale,
  Calculator,
  ArrowLeftRight,
  Shield,
  Brain,
  Settings,
  UserCog,
  ClipboardCheck,
  Factory,
  Mountain,
  Heart,
  Car,
  Monitor,
  Building,
  Cog,
  TrendingUp,
  Store,
  Rocket,
  Users,
  Building2 as BuildingSmall,
  Target,
  HeartHandshake,
  Lightbulb,
  UserCheck,
  BookOpen,
  Award,
  Leaf,
} from 'lucide-react';

export const navigation = {
  main: [
    { name: 'Home', href: '/' },
    {
      name: 'About Us',
      href: '#',
      submenu: [
        { name: 'Our Story', href: '#' },
        { name: 'Vision & Mission', href: '#' },
        { name: 'Founder Profile', href: '#' },
        { name: 'Core Values', href: '#' },
        { name: 'Why Choose Us', href: '#' },
      ],
    },
    {
      name: 'Our Services',
      href: '#',
      submenu: [
        { name: 'Business Valuation', href: '#' },
        { name: 'Insolvency & Bankruptcy', href: '#' },
        { name: 'Cost Audit & Optimization', href: '#' },
        { name: 'Transfer Pricing', href: '#' },
        { name: 'Internal Audit & Risk', href: '#' },
        { name: 'AI Driven Solutions', href: '#' },
        { name: 'ERP Consulting', href: '#' },
        { name: 'Fractional CFO', href: '#' },
        { name: 'Corporate Governance', href: '#' },
      ],
    },
    { name: 'Industries We Serve', href: '#' },
    { name: 'Contact Us', href: '#' },
  ],
  cta: { name: 'Book a Consultation', href: '#' },
};

export const trustIndicators = [
  { value: '25+', label: 'Years of Experience', highlight: true },
  { value: '970+', label: 'Valuations Completed' },
  { value: 'IBBI', label: 'Registered Valuer' },
  { value: 'IBBI', label: 'Registered IP' },
  { value: 'ID', label: 'Independent Director' },
  { value: 'Global', label: 'Experience' },
  { value: 'AI', label: 'Powered Optimization' },
  { value: 'Cross', label: 'Industry Expertise' },
];

export const services = [
  {
    id: 'business-valuation',
    title: 'Business Valuation',
    shortDescription: 'Comprehensive valuation services for mergers, acquisitions, financial reporting, and strategic planning.',
    description: 'Our business valuation services provide defensible, accurate valuations for various purposes including mergers and acquisitions, financial reporting, litigation support, and strategic planning. We use globally recognized methodologies tailored to your specific industry and circumstances.',
    icon: Building2,
    features: [
      'Fairness opinions and purchase price allocations',
      'Intangible asset and intellectual property valuation',
      'Employee stock option plan (ESOP) valuations',
      'Goodwill and impairment testing',
      'Litigation support and expert testimony',
    ],
  },
  {
    id: 'insolvency',
    title: 'Insolvency & Bankruptcy Services',
    shortDescription: 'Expert guidance through complex insolvency proceedings and corporate restructuring.',
    description: 'As IBBI-registered Insolvency Professionals, we provide end-to-end services for corporate insolvency resolution, liquidation, and restructuring. We help stakeholders navigate the complexities of the Insolvency and Bankruptcy Code while maximizing value recovery.',
    icon: Scale,
    features: [
      'Corporate insolvency resolution process management',
      'Liquidation proceedings and asset monetization',
      'Creditor committee advisory services',
      'Resolution plan formulation and evaluation',
      'Stressed asset advisory',
    ],
  },
  {
    id: 'cost-audit',
    title: 'Cost Audit & Cost Optimization',
    shortDescription: 'Identify cost reduction opportunities and improve operational efficiency across your organization.',
    description: 'Our cost audit and optimization services help businesses identify inefficiencies, reduce operational costs, and improve profitability. We combine deep cost accounting expertise with industry benchmarks to deliver actionable recommendations.',
    icon: Calculator,
    features: [
      'Statutory cost audit compliance',
      'Cost reduction and optimization studies',
      'Product and service costing analysis',
      'Break-even and profitability analysis',
      'Activity-based costing implementation',
    ],
  },
  {
    id: 'transfer-pricing',
    title: 'Transfer Pricing',
    shortDescription: 'Navigate international transfer pricing regulations and optimize intercompany transactions.',
    description: 'We provide comprehensive transfer pricing services to help multinational enterprises comply with regulations while optimizing their global tax position. Our solutions ensure arm\'s length compliance and minimize audit risk.',
    icon: ArrowLeftRight,
    features: [
      'Transfer pricing documentation and benchmarking',
      'Advance pricing agreement (APA) assistance',
      'Transfer pricing audit defense',
      'Intercompany pricing strategy',
      'BEPS compliance and Country-by-Country reporting',
    ],
  },
  {
    id: 'internal-audit',
    title: 'Internal Audit & Risk Management',
    shortDescription: 'Strengthen governance and mitigate risks through comprehensive internal audit services.',
    description: 'Our internal audit services go beyond compliance to provide strategic insights that strengthen governance, improve controls, and mitigate risks. We adopt a risk-based approach aligned with your business objectives.',
    icon: Shield,
    features: [
      'Risk-based internal audit',
      'SOX compliance and ICFR assessments',
      'Operational and process audits',
      'Fraud investigation and prevention',
      'Enterprise risk management frameworks',
    ],
  },
  {
    id: 'ai-solutions',
    title: 'AI Driven Business Solutions',
    shortDescription: 'Leverage artificial intelligence to transform operations and gain competitive advantages.',
    description: 'We help businesses harness the power of artificial intelligence to automate processes, enhance decision-making, and create new value. Our AI solutions are tailored to specific industry needs and organizational maturity.',
    icon: Brain,
    features: [
      'Predictive analytics and forecasting',
      'Process automation with AI/ML',
      'Natural language processing solutions',
      'AI-driven financial analysis',
      'Custom AI model development and deployment',
    ],
  },
  {
    id: 'erp-consulting',
    title: 'ERP & Business Process Consulting',
    shortDescription: 'Streamline operations with expert ERP implementation and business process optimization.',
    description: 'We provide end-to-end ERP consulting services from selection and implementation to optimization and support. Our approach ensures your ERP investment delivers maximum value through efficient process integration.',
    icon: Settings,
    features: [
      'ERP selection and implementation advisory',
      'Business process re-engineering',
      'Post-implementation optimization',
      'Integration with existing systems',
      'Change management and training',
    ],
  },
  {
    id: 'fractional-cfo',
    title: 'Fractional CFO Services',
    shortDescription: 'Access senior financial leadership expertise without the full-time cost.',
    description: 'Our fractional CFO services provide growing businesses with access to experienced financial leadership at a fraction of the cost of a full-time CFO. We deliver strategic financial guidance tailored to your stage of growth.',
    icon: UserCog,
    features: [
      'Financial strategy and planning',
      'Cash flow and working capital management',
      'Investor and board reporting',
      'M&A and fundraising support',
      'KPI development and performance tracking',
    ],
  },
  {
    id: 'governance',
    title: 'Corporate Governance & Compliance',
    shortDescription: 'Build robust governance frameworks and ensure regulatory compliance.',
    description: 'We help organizations establish strong corporate governance frameworks that build stakeholder confidence and ensure regulatory compliance. Our services cover board effectiveness, policy frameworks, and compliance management.',
    icon: ClipboardCheck,
    features: [
      'Board advisory and effectiveness',
      'Corporate governance framework design',
      'Compliance program development',
      'Policy and procedure documentation',
      'ESG reporting and sustainability advisory',
    ],
  },
];

export const industries = [
  { name: 'Manufacturing', icon: Factory, description: 'Process optimization, cost management, and valuation for manufacturing businesses.' },
  { name: 'Mining & Natural Resources', icon: Mountain, description: 'Specialized services for extraction industries and resource companies.' },
  { name: 'Healthcare', icon: Heart, description: 'Financial advisory for hospitals, clinics, and healthcare organizations.' },
  { name: 'Automotive', icon: Car, description: 'Expertise across OEMs, suppliers, and automotive services.' },
  { name: 'Information Technology', icon: Monitor, description: 'Valuation and governance for tech companies and startups.' },
  { name: 'Infrastructure', icon: Building, description: 'Advisory for infrastructure projects and construction companies.' },
  { name: 'Engineering', icon: Cog, description: 'Financial services for engineering and project-based businesses.' },
  { name: 'Trading & Distribution', icon: TrendingUp, description: 'Working capital optimization and operational efficiency.' },
  { name: 'Retail', icon: Store, description: 'Strategy, valuation, and cost management for retail businesses.' },
  { name: 'Startups', icon: Rocket, description: 'Fundraising, valuation, and growth advisory for startups.' },
  { name: 'Family Businesses', icon: Users, description: 'Succession planning, governance, and wealth preservation.' },
  { name: 'MSMEs', icon: BuildingSmall, description: 'Scalable solutions for micro, small, and medium enterprises.' },
];

export const coreValues = [
  { name: 'Integrity', icon: Target, description: 'Upholding the highest ethical standards in every engagement.' },
  { name: 'Professional Excellence', icon: Award, description: 'Delivering work of exceptional quality and rigor.' },
  { name: 'Innovation', icon: Lightbulb, description: 'Embracing new approaches and technologies to solve client challenges.' },
  { name: 'Client-Centric Approach', icon: HeartHandshake, description: 'Putting client success at the heart of everything we do.' },
  { name: 'Continuous Learning', icon: BookOpen, description: 'Staying ahead through constant skill development and knowledge enhancement.' },
  { name: 'Accountability', icon: UserCheck, description: 'Taking ownership of our commitments and deliverables.' },
  { name: 'Sustainable Value Creation', icon: Leaf, description: 'Building long-term value for clients, stakeholders, and society.' },
];

export const founder = {
  name: 'Viswanathan Rajagopalan',
  title: 'Founder & Principal Consultant',
  bio: 'With over 25 years of global experience spanning corporate finance, valuation, and business transformation, Mr. Viswanathan Rajagopalan founded VRA to bring world-class advisory services to businesses across industries. His career includes leadership roles in multinational corporations and advisory firms across India, the Middle East, and Southeast Asia.',
  qualifications: [
    'IBBI Registered Valuer (Securities & Financial Assets)',
    'IBBI Registered Insolvency Professional',
    'Cost and Management Accountant (CMA)',
    'Certified Independent Director',
    'Advanced certifications in business valuation and restructuring',
  ],
  experience: [
    'Led 970+ business valuation engagements across sectors',
    'Managed complex insolvency and restructuring mandates',
    'Advised Fortune 500 and mid-market companies on strategic transactions',
    'Implemented transformation initiatives yielding measurable results',
  ],
};

export const companyInfo = {
  name: 'Viswanathan R Associates',
  shortName: 'VRA',
  tagline: 'Corporate Finance. Business Transformation. Value Creation.',
  description: 'Strategic Financial Advisory for Businesses, Investors, Banks, and Corporate Leaders.',
  vision: 'To be the most trusted partner for organizations seeking exceptional financial advisory and business transformation services, recognized for integrity, expertise, and sustainable value creation.',
  mission: 'We empower businesses with strategic financial insights and innovative solutions that drive growth, optimize operations, and create lasting value. Through expert valuation, restructuring, cost optimization, and governance services, we help our clients navigate complexity and achieve their strategic objectives.',
  story: 'Founded on the principle that every business deserves access to world-class financial advisory, Viswanathan R Associates was established to bridge the gap between large consulting firms and growing enterprises. Our founder\'s decades of experience across global markets and diverse industries informs an approach that combines deep technical expertise with practical, actionable recommendations.',
  address: {
    line1: '123 Financial District',
    line2: 'Anna Salai, Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600002',
    country: 'India',
  },
  contact: {
    email: 'info@vrassociates.in',
    phone: '+91 44 1234 5678',
    mobile: '+91 98765 43210',
  },
  social: {
    facebook: 'https://www.facebook.com/vrassociates',
    instagram: 'https://www.instagram.com/vrassociates',
    linkedin: 'https://www.linkedin.com/company/vrassociates',
    twitter: 'https://www.twitter.com/vrassociates',
  },
};

export const whyChooseUs = [
  { title: 'Unmatched Expertise', description: '25+ years of cross-industry experience with 970+ successful valuations.' },
  { title: 'Regulatory Credentials', description: 'IBBI-registered Valuer and Insolvency Professional with recognized qualifications.' },
  { title: 'Global Perspective', description: 'International experience across diverse markets and regulatory environments.' },
  { title: 'AI-Powered Insights', description: 'Leveraging technology to deliver deeper insights and optimize outcomes.' },
  { title: 'Client-Focused Approach', description: 'Customized solutions aligned with your specific business context and objectives.' },
  { title: 'End-to-End Support', description: 'From diagnosis to implementation, we partner with you throughout the journey.' },
];
